#!/bin/bash

ARGS="-ti --rm --hostname=builder --name=builder"
CMAKE="cmake"
CMAKE_ARGS=".. -G Ninja"
CONTAINER="builder"
RUN="docker run"

case $1 in
  "test")
    case $2 in
      "cmake")
        mkdir -p test/build
        $RUN $ARGS \
          -v `cd test; pwd`:/code \
          --workdir=/code/build \
          --entrypoint=$CMAKE $CONTAINER $CMAKE_ARGS
      ;;
      "ninja")
        $RUN $ARGS\
          -v `cd test; pwd`:/code \
          --workdir=/code/build \
          --entrypoint=$NINJA $CONTAINER
    esac
  ;;
  "run")
    $RUN $ARGS --entrypoint=bash $CONTAINER
  ;;
  *) echo "usage build <component> [cmake|ninja|test]"
  ;;
esac
