#!/bin/bash

apt-get update && apt-get install -y \
  libssl1.0.0 \
  libkrb5-3 \
  libsasl2-2 \
  libnuma1 \
  libcap2 \
  libevent-2.0-5 \
  libjemalloc1 \
  libsnappy1v5 \
  ca-certificates \
  net-tools \
  iputils-ping \
  tmux

