#!/bin/sh

openssl req -x509 \
  -newkey rsa:2048 \
  -keyout key.pem \
  -out cert.pem \
  -days 365 \
  -nodes \
  -subj "/C=US/ST=California/L=Los Angeles/O=USC ISI/OU=Deter/CN=${1}.marina.deterlab.net"

